SRE 1518 Show Circle CI deployment progress
snapsheet/trigger-circleci-pipeline-action pull request #7
Opened 2023-03-21 21:26 UTC by paikattilrohin

Closes https://snapsheettech.atlassian.net/browse/SRE-1518

## What
Implements the description outlined in https://github.com/CircleCI-Public/trigger-circleci-pipeline-action/issues/28 to add Outputs to the GitHub Action in order to enable downstream projects to pull the pipeline number and id.

**Example GitHub Job Steps**
```yaml
      - name: Deploying to ${{ inputs.environment_name }} with CircleCI Pipeline
        uses:  snapsheet/trigger-circleci-pipeline-action@SRE-1517-circle-ci-action-pipeline-outputs
        with:
          GHA_Data: ${{ toJSON(inputs) }}
          GHA_Meta: ${{ inputs.environment_name }}
          CCI_Context: ${{ fromJson(steps.environment_config.outputs.json_string).context }}
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
      - name: Check CircleCI Outputs
        run: |
          echo "id: ${{ steps.cci_pipeline.outputs.id }}"
          echo "state: ${{ steps.cci_pipeline.outputs.state }}"
          echo "created_at: ${{ steps.cci_pipeline.outputs.created_at }}"
          echo "number: ${{ steps.cci_pipeline.outputs.number }}"

```

## Why
This enables projects to query the CircleCI API for more information in downstream GitHub steps, jobs, and workflows.

## How
* Upgrade the NPM package for @actions/core to 1.10.0, so that it uses the [recommendations listed here](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).
* Add the Outputs to the `action.yml` file.
* Set the outputs in the source.

## Testing
Check out a branch of your project that uses this GitHub Action.

Update the action to reference this branch:
```yaml
uses:  snapsheet/trigger-circleci-pipeline-action@SRE-1518-show-circle-ci-deployment-progress
```

2023-03-22 16:51 UTC, whatisdot requested changes, later dismissed

2023-03-22 16:51 UTC, whatisdot commented on index.js
> +    info(
Can you test using `notice` for this? It will make it stand out more.

2023-03-22 16:51 UTC, whatisdot commented on index.js
> +      "https://circleci.com/api/v2/pipeline/" + response.data.id + "/workflow";
You should use a string interpolation:
```ts
        workFlowUrl =`https://circleci.com/api/v2/pipeline/${response.data.id}/workflow`;
```

2023-03-22 16:51 UTC, whatisdot commented on index.js
> +        pipelineComplete = true;
According to [the CircleCI API](https://circleci.com/docs/api/v2/index.html#operation/getWorkflowById), possible statuses include:
> Enum: "success" "running" "not_run" "failed" "error" "failing" "on_hold" "canceled" "unauthorized" 

I found [this documentation for workflow states](https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/workflows.md), which also lists a "needs setup" step not documented in the API... 🤔

Based on the two of these, we should continue polling when states are one of the following:
* `running`
* `not_run` (Workflow was never started)
* `on_hold` (A job in the workflow is waiting for approval)

You should check for any status within that set.

2023-03-22 16:51 UTC, whatisdot commented on index.js
> +          setFailed("CircleCI Pipeline failed");
You should add the workflow state to the log message.

2023-03-22 16:51 UTC, whatisdot commented on index.js
> +if (keepPolling == "true") {
I would combine `pipelineComplete` with `keepPolling`, instead of managing two different flags.

2023-03-22 18:19 UTC, whatisdot commented on index.js
> +if (followWorkflow) {
I think you only need to wrap the `info` call. The `setInterval` should immedately be unset if `followWorkflow` is false.

```typescript
if (followWorkflow) {
  info("Polling CircleCI Workflow");
}

const checkWebsiteStatus = setInterval(() => {
  if (!followWorkflow) {
    clearInterval(checkWebsiteStatus);
  } else {
    pollWorkflow();
  }
}, pollInterval);
```

2023-03-22 19:20 UTC, whatisdot commented on index.js
> +        response.data.items[0].status != "running" ||
I think you wanted boolean &&

"If the status isn't running, and isn't not_run, and isn't on_hold..."

I think you could also one-line this by using the `includes` method:
```typescript
if( ! ["not_run", "on_hold", "running"].includes(response.data.items[0].status) ) {
```

2023-03-22 20:00 UTC, whatisdot approved these changes
Tested this on an example project and it works as expected with both success and failure cases, along with polling and default non-polling behavior.

2023-03-23 18:19 UTC, d10zero approved these changes
Testing in VBE qa7 and works as expected. Nice !

2023-03-23 19:22 UTC, whatisdot approved these changes
Tested this and it works as expected. Now actions can wait until CircleCI finishes. Very nice :)

2023-03-23 19:25 UTC, merged